
#ifndef HELP
#define HELP

#include <stdbool.h>
#include <string.h>
#include <Windows.h>
#include <stdio.h>
#include <stdlib.h>
#include "../library/ui.cpp"
#include "../iGraphics.h"
#include "settings.cpp"


Ui help_title = {
    xpos( 99,"left",&help_title),
    ypos( 8,"top",&help_title),
    30,
    200,
    "INSTRUCTIONS",
    { 82 ,  3,  252},
     18,
    "center-x",
     false,
};




void help_page()
{
    render(&help_title);
    render(&back_ui);
    iText(150,WINDOW_HEIGHT-100,"SINGLE PLAYER",GLUT_BITMAP_HELVETICA_18);
    iText(150,WINDOW_HEIGHT-140,"PRESS ARROW UP KEY TO MOVE SNAKE UP ",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-170,"PRESS ARROW UP KEY TO MOVE SNAKE UP ",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-200,"PRESS ARROW UP KEY TO MOVE SNAKE UP ",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-230,"PRESS ARROW UP KEY TO MOVE SNAKE UP ",GLUT_BITMAP_9_BY_15);

    iText(150,WINDOW_HEIGHT-270,"TWO PLAYER",GLUT_BITMAP_HELVETICA_18);
    iText(150,WINDOW_HEIGHT-310,"PRESS ARROW UP KEY TO MOVE SNAKE_1 UP ",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-340,"PRESS ARROW DOWN KEY TO MOVE SNAKE_1 DOWN ",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-370,"PRESS ARROW LEFT KEY TO MOVE SNAKE_1 LEFT",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-400,"PRESS ARROW RIGHT KEY TO MOVE SNAKE_1 RIGHT",GLUT_BITMAP_9_BY_15);

    iText(550,WINDOW_HEIGHT-310,"PRESS W KEY TO MOVE SNAKE_2 UP ",GLUT_BITMAP_9_BY_15);
    iText(550,WINDOW_HEIGHT-340,"PRESS S KEY TO MOVE SNAKE_2 DOWN ",GLUT_BITMAP_9_BY_15);
    iText(550,WINDOW_HEIGHT-370,"PRESS A KEY TO MOVE SNAKE_2 LEFT ",GLUT_BITMAP_9_BY_15);
    iText(550,WINDOW_HEIGHT-400,"PRESS D KEY TO MOVE SNAKE_2 RIGHT ",GLUT_BITMAP_9_BY_15);


    iText(150,WINDOW_HEIGHT-440,"SCORE AND LIFE",GLUT_BITMAP_HELVETICA_18);
    iText(150,WINDOW_HEIGHT-480,"EATING FOOD WILL INCREMENT ONE SCORE",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-510,"BONUS FOOD WILL APPEAR AFTER 4 FOOD CONSUMPTION",GLUT_BITMAP_9_BY_15);
    iText(150,WINDOW_HEIGHT-540,"COLLIDING WITH BORDERLINE , OBSTACLES AND OWN BODY WILL DECREASE ONE LIFE",GLUT_BITMAP_9_BY_15);
    


}


void help_page_control(int mx, int my)
{
    if(click_or_hover(mx,my,back_ui))
    {
        page_state=0;
    }
}

#endif